language: go
env:
  global:
  - IMAGE_NAME=kodek/tesler
  - REGISTRY_USER=kodek
  - secure: G0JqAbCGff92cDcjfOWXpXXLfcAQMYrA6Spr2DccXv3aWB5tC5qNMr8mHED+rR23HRceeCRQgHjHJn8gbkNpnZFYqBbPzR74Y44q2W55zHFth0ZVg7YVUb+bdEltXs4Uy0n2xoFcESmXbomM0O87vzGboQSm99ShLrLHRN+pg3Ti882efOke2FwUs/qzg/N17HcFCkzxWPlbd22YlatPVupb94272mk6vHiwVnvRdDhbBmy0ugtQXI8nYNyYG0cbqro39NM5g/sI2Yu/1pxVwGJjJKY1kJb9f1uMFUKeDOZDmRI/nQnyXB06kVJs7K+RN8KvVW0btEeGnCyRFn/TZnlKOFLXVOEwvDchTU6vWVdnHvSJbKeZN/PMuOZEaY+RXE81PblHIZAwp+pHvrFFGqzk0VUsJVjyWXlZW4kf+fgDQ5oSj6J2vzSOhepKcUIKE9pEo6pp6hVFpGO3bJJJzagPJJN4YVFdMAm2wJ6NzPZEMVtsiR5JUM+QHxyd+4lkj6pyL7/5PkD3rrk7h4kdgU8qBbFcadImZbWg6Y1IgPavfEOZPjs7KUw29aXENCM//MJycwg5sZs+pG5XJMbn7PhMPtmmNi0OH0wDwxq1xR+tSqachbN5OfEeZWZZ1IQqGf2cRcBd2WtYmOOe8QhpGIlEeuJCk7lPqZnX6j+8J88=
go:
- '1.11'
script:
- go test ./...
- go build -o ./recorder_main recorder/server/recorder_main.go
- docker build -t "${IMAGE_NAME}:latest" --build-arg "travis_commit=${TRAVIS_COMMIT}"
  -f recorder/Dockerfile .
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker tag "$IMAGE_NAME" "$IMAGE_NAME:latest"
- docker tag "$IMAGE_NAME" "$IMAGE_NAME:${TRAVIS_BRANCH}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_BRANCH}"
  on:
    branch: master
